name: Build Web Page Screensaver

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'));

      - name: Install .NET Framework Developer Pack
        run: choco install netfx-4.8-devpack -y

      - name: Install .NET SDK 6.0
        run: choco install dotnet-sdk --version=6.0.413 -y

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install Dependencies
        run: |
          dotnet add package Microsoft.Web.WebView2 --version 1.0.1370.28
          dotnet add package System.Runtime.WindowsRuntime --version 4.0.0
          dotnet add package Microsoft.Windows.Compatibility --version 6.0.4

      - name: Build Solution
        run: dotnet build Web-Page-Screensaver.sln --configuration Release --verbosity detailed

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WebPageScreensaver
          path: bin/Release
